// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webuimessages_base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_webuimessages_5fbase_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_webuimessages_5fbase_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "enums.pb.h"
#include "steammessages_base.pb.h"
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_webuimessages_5fbase_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_webuimessages_5fbase_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_webuimessages_5fbase_2eproto;
class WebUINoResponse;
struct WebUINoResponseDefaultTypeInternal;
extern WebUINoResponseDefaultTypeInternal _WebUINoResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::WebUINoResponse* Arena::CreateMaybeMessage<::WebUINoResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum EClientExecutionSite : int {
  k_EClientExecutionSiteInvalid = 0,
  k_EClientExecutionSiteSteamUI = 1,
  k_EClientExecutionSiteClientdll = 2,
  k_EClientExecutionSiteAny = 3
};
bool EClientExecutionSite_IsValid(int value);
constexpr EClientExecutionSite EClientExecutionSite_MIN = k_EClientExecutionSiteInvalid;
constexpr EClientExecutionSite EClientExecutionSite_MAX = k_EClientExecutionSiteAny;
constexpr int EClientExecutionSite_ARRAYSIZE = EClientExecutionSite_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EClientExecutionSite_descriptor();
template<typename T>
inline const std::string& EClientExecutionSite_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EClientExecutionSite>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EClientExecutionSite_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EClientExecutionSite_descriptor(), enum_t_value);
}
inline bool EClientExecutionSite_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EClientExecutionSite* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EClientExecutionSite>(
    EClientExecutionSite_descriptor(), name, value);
}
// ===================================================================

class WebUINoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:WebUINoResponse) */ {
 public:
  inline WebUINoResponse() : WebUINoResponse(nullptr) {}
  explicit constexpr WebUINoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WebUINoResponse(const WebUINoResponse& from);
  WebUINoResponse(WebUINoResponse&& from) noexcept
    : WebUINoResponse() {
    *this = ::std::move(from);
  }

  inline WebUINoResponse& operator=(const WebUINoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WebUINoResponse& operator=(WebUINoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WebUINoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const WebUINoResponse* internal_default_instance() {
    return reinterpret_cast<const WebUINoResponse*>(
               &_WebUINoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(WebUINoResponse& a, WebUINoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(WebUINoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WebUINoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WebUINoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<WebUINoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const WebUINoResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const WebUINoResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "WebUINoResponse";
  }
  protected:
  explicit WebUINoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:WebUINoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_webuimessages_5fbase_2eproto;
};
// ===================================================================

static const int kWebuiServiceExecutionSiteFieldNumber = 70000;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::EClientExecutionSite, ::EClientExecutionSite_IsValid>, 14, false >
  webui_service_execution_site;
static const int kWebuiMethodExecutionSiteFieldNumber = 70000;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::EClientExecutionSite, ::EClientExecutionSite_IsValid>, 14, false >
  webui_method_execution_site;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WebUINoResponse

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::EClientExecutionSite> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EClientExecutionSite>() {
  return ::EClientExecutionSite_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_webuimessages_5fbase_2eproto
