// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webuimessages_base.proto

#include "webuimessages_base.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr WebUINoResponse::WebUINoResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct WebUINoResponseDefaultTypeInternal {
  constexpr WebUINoResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~WebUINoResponseDefaultTypeInternal() {}
  union {
    WebUINoResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT WebUINoResponseDefaultTypeInternal _WebUINoResponse_default_instance_;
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_webuimessages_5fbase_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_webuimessages_5fbase_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_webuimessages_5fbase_2eproto = nullptr;

const uint32_t TableStruct_webuimessages_5fbase_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::WebUINoResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::WebUINoResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_WebUINoResponse_default_instance_),
};

const char descriptor_table_protodef_webuimessages_5fbase_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030webuimessages_base.proto\032\013enums.proto\032"
  "\030steammessages_base.proto\032 google/protob"
  "uf/descriptor.proto\"\021\n\017WebUINoResponse*\240"
  "\001\n\024EClientExecutionSite\022!\n\035k_EClientExec"
  "utionSiteInvalid\020\000\022!\n\035k_EClientExecution"
  "SiteSteamUI\020\001\022#\n\037k_EClientExecutionSiteC"
  "lientdll\020\002\022\035\n\031k_EClientExecutionSiteAny\020"
  "\003:}\n\034webui_service_execution_site\022\037.goog"
  "le.protobuf.ServiceOptions\030\360\242\004 \001(\0162\025.ECl"
  "ientExecutionSite:\035k_EClientExecutionSit"
  "eSteamUI:{\n\033webui_method_execution_site\022"
  "\036.google.protobuf.MethodOptions\030\360\242\004 \001(\0162"
  "\025.EClientExecutionSite:\035k_EClientExecuti"
  "onSiteInvalidB\005H\001\200\001\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_webuimessages_5fbase_2eproto_deps[3] = {
  &::descriptor_table_enums_2eproto,
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
  &::descriptor_table_steammessages_5fbase_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_webuimessages_5fbase_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_webuimessages_5fbase_2eproto = {
  false, false, 540, descriptor_table_protodef_webuimessages_5fbase_2eproto, "webuimessages_base.proto", 
  &descriptor_table_webuimessages_5fbase_2eproto_once, descriptor_table_webuimessages_5fbase_2eproto_deps, 3, 1,
  schemas, file_default_instances, TableStruct_webuimessages_5fbase_2eproto::offsets,
  file_level_metadata_webuimessages_5fbase_2eproto, file_level_enum_descriptors_webuimessages_5fbase_2eproto, file_level_service_descriptors_webuimessages_5fbase_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_webuimessages_5fbase_2eproto_getter() {
  return &descriptor_table_webuimessages_5fbase_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_webuimessages_5fbase_2eproto(&descriptor_table_webuimessages_5fbase_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EClientExecutionSite_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_webuimessages_5fbase_2eproto);
  return file_level_enum_descriptors_webuimessages_5fbase_2eproto[0];
}
bool EClientExecutionSite_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class WebUINoResponse::_Internal {
 public:
};

WebUINoResponse::WebUINoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:WebUINoResponse)
}
WebUINoResponse::WebUINoResponse(const WebUINoResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:WebUINoResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WebUINoResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WebUINoResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata WebUINoResponse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_webuimessages_5fbase_2eproto_getter, &descriptor_table_webuimessages_5fbase_2eproto_once,
      file_level_metadata_webuimessages_5fbase_2eproto[0]);
}
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::EClientExecutionSite, ::EClientExecutionSite_IsValid>, 14, false >
  webui_service_execution_site(kWebuiServiceExecutionSiteFieldNumber, static_cast< ::EClientExecutionSite >(1));
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::EClientExecutionSite, ::EClientExecutionSite_IsValid>, 14, false >
  webui_method_execution_site(kWebuiMethodExecutionSiteFieldNumber, static_cast< ::EClientExecutionSite >(0));

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::WebUINoResponse* Arena::CreateMaybeMessage< ::WebUINoResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WebUINoResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
